export type PublicQrLanguage = "pt-BR" | "en" | "es";

const copy = {
  "pt-BR": {
    initialStatus: "Escolha itens do cardápio ou chame o atendimento.",
    invalidSecure: "Este QR é inválido, foi revogado ou não pertence mais a esta mesa.",
    invalidLegacy: "Este QR é inválido ou o atendimento está indisponível no momento.",
    unavailable: "QR indisponível",
    unavailableTitle: "Não foi possível abrir esta mesa",
    askTeam: "Peça à equipe do estabelecimento um material atualizado.",
    loading: "Carregando QR",
    checking: "Consultando o atendimento desta mesa...",
    table: "Mesa",
    heroDefault: "Monte seu pedido, chame atendimento ou solicite a pré-conta da mesa.",
    coverAlt: "Imagem do estabelecimento",
    highlights: "Destaques da casa",
    menu: "Cardápio",
    orderTitle: "Pedido da mesa",
    fullMenu: "Cardápio completo",
    searchPlaceholder: "Buscar prato, bebida ou sobremesa",
    all: "Todos",
    recommended: "Recomendado",
    noItems: "Nenhum item encontrado para esse filtro.",
    tab: "Comanda",
    currentTab: "Comanda atual",
    itemCount: (count: number) => `${count} item(ns)`,
    emptyCart: "Nenhum item selecionado ainda.",
    guestLabel: "Identificação do pedido (opcional)",
    guestPlaceholder: "Apelido ou assento 3",
    guestHelp: "Ajuda a equipe a encontrar seu pedido sem pedir dados pessoais.",
    status: "Status",
    identification: "Identificação",
    received: "Recebido",
    remaining: "Restante",
    orderTracking: "Acompanhamento do pedido",
    sendOrder: "Enviar pedido",
    callWaiter: "Chamar garçom",
    callWaiterHelp: "Solicitação registrada para o painel do salão.",
    quickReasons: "Como podemos ajudar?",
    preBill: "Pedir pré-conta",
    preBillReady: "O caixa recebe o pedido de fechamento da mesa.",
    preBillEmpty: "A comanda ainda não possui consumo registrado.",
    tableSummary: "Resumo da mesa",
    tableSummaryHelp: "Abra um documento visual com os itens montados e total estimado.",
    service: "Atendimento",
    technology: "Conheça a tecnologia deste atendimento",
    technologySentence: "Tecnologia GiroMesa para uma operação mais simples.",
    close: "Fechar",
    loadingOptions: "Carregando opções...",
    noOptions: "Nenhuma opção de personalização disponível.",
    required: "Obrigatório",
    optional: "Opcional",
    upTo: (count: number) => `(até ${count})`,
    addToOrder: "Adicionar ao pedido",
    genericFailure: "Falha ao executar ação.",
    addAtLeastOne: "Adicione pelo menos um item ao pedido.",
    inactiveTable: "O atendimento desta mesa ainda não foi ativado pela equipe.",
    chooseRequired: (groups: string) => `Selecione pelo menos uma opção em: ${groups}`,
    orderSent: (id: string) => `Pedido ${id} enviado para o salão.`,
    waiterCalled: "Garçom chamado. A solicitação ficou registrada no painel.",
    preBillRequested: "Pré-conta solicitada. O caixa recebeu o pedido de fechamento.",
    noConsumption: "A comanda desta mesa ainda não possui consumo registrado.",
    addForSummary: "Adicione itens para visualizar o resumo da mesa.",
    popupBlocked: "Não foi possível abrir a janela de resumo.",
    summaryOpened: "Resumo visual da mesa aberto para impressão.",
    summaryDraftSubtitle: "Conferência visual do pedido montado antes do envio ou da pré-conta.",
    summaryOrderSubtitle: "Resumo da comanda atual carregado do atendimento do estabelecimento.",
    summaryDocument: "Resumo da mesa",
    customer: "Cliente",
    qrService: "Atendimento via QR",
    generatedAt: "Gerado em",
    items: "Itens",
    lines: "Linhas",
    tabTotal: "Total da comanda",
    estimatedTotal: "Total estimado",
    selectedItems: "Itens selecionados",
    quantity: "Qtd",
    item: "Item",
    unitPrice: "Unitário",
    total: "Total",
    nonFiscalSummary:
      "Resumo sem valor fiscal nem dados pessoais; a origem comercial registra somente contagem agregada.",
  },
  en: {
    initialStatus: "Choose menu items or request assistance.",
    invalidSecure: "This QR code is invalid, revoked, or no longer belongs to this table.",
    invalidLegacy: "This QR code is invalid or service is currently unavailable.",
    unavailable: "QR unavailable",
    unavailableTitle: "We could not open this table",
    askTeam: "Ask the venue staff for an updated QR code.",
    loading: "Loading QR",
    checking: "Checking this table service...",
    table: "Table",
    heroDefault: "Place an order, request assistance, or ask for the bill.",
    coverAlt: "Venue image",
    highlights: "Venue highlights",
    menu: "Menu",
    orderTitle: "Table order",
    fullMenu: "Full menu",
    searchPlaceholder: "Search food, drinks, or desserts",
    all: "All",
    recommended: "Recommended",
    noItems: "No items match this filter.",
    tab: "Tab",
    currentTab: "Current tab",
    itemCount: (count: number) => `${count} item(s)`,
    emptyCart: "No items selected yet.",
    guestLabel: "Order identification (optional)",
    guestPlaceholder: "Nickname or seat 3",
    guestHelp: "Helps staff locate your order without requesting personal data.",
    status: "Status",
    identification: "Identification",
    received: "Paid",
    remaining: "Remaining",
    orderTracking: "Order progress",
    sendOrder: "Send order",
    callWaiter: "Call staff",
    callWaiterHelp: "Your request is sent to the floor team.",
    quickReasons: "How can we help?",
    preBill: "Request bill",
    preBillReady: "The cashier receives your request to close the table.",
    preBillEmpty: "There is no recorded consumption on this tab yet.",
    tableSummary: "Table summary",
    tableSummaryHelp: "Open a visual summary of selected items and estimated total.",
    service: "Service",
    technology: "Discover the technology behind this service",
    technologySentence: "GiroMesa technology for simpler hospitality operations.",
    close: "Close",
    loadingOptions: "Loading options...",
    noOptions: "No customization options are available.",
    required: "Required",
    optional: "Optional",
    upTo: (count: number) => `(up to ${count})`,
    addToOrder: "Add to order",
    genericFailure: "Unable to complete the action.",
    addAtLeastOne: "Add at least one item to your order.",
    inactiveTable: "This table has not been activated by staff yet.",
    chooseRequired: (groups: string) => `Choose at least one option for: ${groups}`,
    orderSent: (id: string) => `Order ${id} sent to the venue.`,
    waiterCalled: "Staff requested. Your request is visible to the floor team.",
    preBillRequested: "Bill requested. The cashier has received your request.",
    noConsumption: "There is no recorded consumption on this table yet.",
    addForSummary: "Add items to view the table summary.",
    popupBlocked: "The summary window could not be opened.",
    summaryOpened: "Table summary opened for printing.",
    summaryDraftSubtitle: "Visual review of the order before sending it or requesting the bill.",
    summaryOrderSubtitle: "Current tab summary loaded from the venue service.",
    summaryDocument: "Table summary",
    customer: "Customer",
    qrService: "QR service",
    generatedAt: "Generated at",
    items: "Items",
    lines: "Lines",
    tabTotal: "Tab total",
    estimatedTotal: "Estimated total",
    selectedItems: "Selected items",
    quantity: "Qty",
    item: "Item",
    unitPrice: "Unit price",
    total: "Total",
    nonFiscalSummary:
      "Non-fiscal summary without personal data; commercial origin records aggregate counts only.",
  },
  es: {
    initialStatus: "Elige productos del menú o solicita atención.",
    invalidSecure: "Este código QR no es válido, fue revocado o ya no pertenece a esta mesa.",
    invalidLegacy: "Este código QR no es válido o el servicio no está disponible.",
    unavailable: "QR no disponible",
    unavailableTitle: "No fue posible abrir esta mesa",
    askTeam: "Solicita al equipo del establecimiento un código QR actualizado.",
    loading: "Cargando QR",
    checking: "Consultando el servicio de esta mesa...",
    table: "Mesa",
    heroDefault: "Haz tu pedido, solicita atención o pide la cuenta.",
    coverAlt: "Imagen del establecimiento",
    highlights: "Destacados del establecimiento",
    menu: "Menú",
    orderTitle: "Pedido de la mesa",
    fullMenu: "Menú completo",
    searchPlaceholder: "Buscar comida, bebida o postre",
    all: "Todos",
    recommended: "Recomendado",
    noItems: "No hay productos para este filtro.",
    tab: "Cuenta",
    currentTab: "Cuenta actual",
    itemCount: (count: number) => `${count} producto(s)`,
    emptyCart: "Aún no seleccionaste productos.",
    guestLabel: "Identificación del pedido (opcional)",
    guestPlaceholder: "Apodo o asiento 3",
    guestHelp: "Ayuda al equipo a localizar tu pedido sin solicitar datos personales.",
    status: "Estado",
    identification: "Identificación",
    received: "Recibido",
    remaining: "Pendiente",
    orderTracking: "Seguimiento del pedido",
    sendOrder: "Enviar pedido",
    callWaiter: "Llamar al camarero",
    callWaiterHelp: "La solicitud se envía al equipo de sala.",
    quickReasons: "¿Cómo podemos ayudarte?",
    preBill: "Pedir la cuenta",
    preBillReady: "La caja recibe la solicitud de cierre de la mesa.",
    preBillEmpty: "La cuenta aún no tiene consumo registrado.",
    tableSummary: "Resumen de la mesa",
    tableSummaryHelp: "Abre un resumen visual de los productos y el total estimado.",
    service: "Atención",
    technology: "Conoce la tecnología de este servicio",
    technologySentence: "Tecnología GiroMesa para una operación más simple.",
    close: "Cerrar",
    loadingOptions: "Cargando opciones...",
    noOptions: "No hay opciones de personalización disponibles.",
    required: "Obligatorio",
    optional: "Opcional",
    upTo: (count: number) => `(hasta ${count})`,
    addToOrder: "Agregar al pedido",
    genericFailure: "No fue posible completar la acción.",
    addAtLeastOne: "Agrega al menos un producto al pedido.",
    inactiveTable: "El equipo aún no activó la atención de esta mesa.",
    chooseRequired: (groups: string) => `Elige al menos una opción en: ${groups}`,
    orderSent: (id: string) => `Pedido ${id} enviado al establecimiento.`,
    waiterCalled: "Camarero solicitado. El equipo de sala recibió tu solicitud.",
    preBillRequested: "Cuenta solicitada. La caja recibió tu solicitud.",
    noConsumption: "Esta mesa aún no tiene consumo registrado.",
    addForSummary: "Agrega productos para ver el resumen de la mesa.",
    popupBlocked: "No fue posible abrir la ventana de resumen.",
    summaryOpened: "Resumen de la mesa abierto para imprimir.",
    summaryDraftSubtitle: "Revisión visual del pedido antes de enviarlo o pedir la cuenta.",
    summaryOrderSubtitle:
      "Resumen de la cuenta actual cargado desde el servicio del establecimiento.",
    summaryDocument: "Resumen de la mesa",
    customer: "Cliente",
    qrService: "Atención por QR",
    generatedAt: "Generado el",
    items: "Productos",
    lines: "Líneas",
    tabTotal: "Total de la cuenta",
    estimatedTotal: "Total estimado",
    selectedItems: "Productos seleccionados",
    quantity: "Cant.",
    item: "Producto",
    unitPrice: "Precio unitario",
    total: "Total",
    nonFiscalSummary:
      "Resumen no fiscal sin datos personales; el origen comercial registra solo conteos agregados.",
  },
} as const;

export function normalizePublicQrLanguage(value: unknown): PublicQrLanguage {
  return value === "en" || value === "es" ? value : "pt-BR";
}

export function getPublicQrCopy(value: unknown) {
  return copy[normalizePublicQrLanguage(value)];
}

const orderStatuses: Record<PublicQrLanguage, Record<string, string>> = {
  "pt-BR": {
    draft: "Rascunho",
    opened: "Recebido",
    sent_to_kitchen: "Enviado para produção",
    preparing: "Em preparo",
    ready: "Pronto para servir",
    served: "Entregue à mesa",
    waiting_payment: "Aguardando pagamento",
    partially_paid: "Pagamento parcial",
    paid: "Pago",
    canceled: "Cancelado",
    refunded: "Estornado",
  },
  en: {
    draft: "Draft",
    opened: "Received",
    sent_to_kitchen: "Sent to production",
    preparing: "Preparing",
    ready: "Ready to serve",
    served: "Served",
    waiting_payment: "Awaiting payment",
    partially_paid: "Partially paid",
    paid: "Paid",
    canceled: "Canceled",
    refunded: "Refunded",
  },
  es: {
    draft: "Borrador",
    opened: "Recibido",
    sent_to_kitchen: "Enviado a producción",
    preparing: "En preparación",
    ready: "Listo para servir",
    served: "Entregado",
    waiting_payment: "Esperando pago",
    partially_paid: "Pago parcial",
    paid: "Pagado",
    canceled: "Cancelado",
    refunded: "Reembolsado",
  },
};

const serviceStatuses: Record<PublicQrLanguage, Record<string, string>> = {
  "pt-BR": {
    pending: "aguardando a equipe",
    acknowledged: "equipe a caminho",
    resolved: "resolvido",
    canceled: "cancelado",
    fallback: "em acompanhamento",
  },
  en: {
    pending: "waiting for staff",
    acknowledged: "staff is on the way",
    resolved: "resolved",
    canceled: "canceled",
    fallback: "in progress",
  },
  es: {
    pending: "esperando al equipo",
    acknowledged: "el equipo está en camino",
    resolved: "resuelto",
    canceled: "cancelado",
    fallback: "en seguimiento",
  },
};

export function publicOrderStatusLabel(status: string, language: unknown) {
  return orderStatuses[normalizePublicQrLanguage(language)][status] ?? status;
}

export function publicServiceStatusLabel(status: string, language: unknown) {
  const labels = serviceStatuses[normalizePublicQrLanguage(language)];
  return labels[status] ?? labels.fallback;
}

const timeline: Record<PublicQrLanguage, Record<string, string>> = {
  "pt-BR": {
    received: "Pedido recebido",
    sent_to_kitchen: "Enviado para produção",
    preparing: "Em preparo",
    ready: "Pronto",
    served: "Servido",
    canceled: "Cancelado",
  },
  en: {
    received: "Order received",
    sent_to_kitchen: "Sent to production",
    preparing: "Preparing",
    ready: "Ready",
    served: "Served",
    canceled: "Canceled",
  },
  es: {
    received: "Pedido recibido",
    sent_to_kitchen: "Enviado a producción",
    preparing: "En preparación",
    ready: "Listo",
    served: "Servido",
    canceled: "Cancelado",
  },
};

export function publicTimelineLabel(key: string, fallback: string, language: unknown) {
  return timeline[normalizePublicQrLanguage(language)][key] ?? fallback;
}

export function formatPublicQrMoney(cents: number, language: unknown) {
  return new Intl.NumberFormat(normalizePublicQrLanguage(language), {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}
